In [0]:
# Importando as bibliotecas que serão usadas no laboratório.

from pyspark.sql import *
from pyspark.sql.types import *
from pyspark.sql.functions import *

In [0]:
path = '/FileStore/tables/titanic.csv'
file_type = 'csv'

df_titanic = spark \
             .read.format(file_type) \
             .option("inferSchema" , "True") \
             .option("header" , "True") \
             .option("sep", ",") \
             .csv(path)

In [0]:
#Nome das Colunas
df_titanic.columns

Out[19]: ['PassengerId',
 'Survived',
 'Classe',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [0]:
#Exibindo o dataframe
df_titanic.show(5)
# df_titanic.head(5) - Pandas

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| null|       S|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
only showing top 5 rows

In [0]:
# verificando o tipo de colunas
df_titanic.printSchema()
#df_titanic.info() - pandas

root
 |-- PassengerId: integer (nullable = true)
 |-- Survived: integer (nullable = true)
 |-- Pclass: integer (nullable = true)
 |-- Name: string (nullable = true)
 |-- Sex: string (nullable = true)
 |-- Age: double (nullable = true)
 |-- SibSp: integer (nullable = true)
 |-- Parch: integer (nullable = true)
 |-- Ticket: string (nullable = true)
 |-- Fare: double (nullable = true)
 |-- Cabin: string (nullable = true)
 |-- Embarked: string (nullable = true)

In [0]:
#Renomeando colunas
df_titanic = df_titanic.withColumnRenamed("Pclass" , "Classe")

In [0]:
#Mostrando dataframe com filtro
df_titanic.filter(df_titanic['Survived'] == 1).show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+--------+-----+--------+
|PassengerId|Survived|Classe|                Name|   Sex| Age|SibSp|Parch|          Ticket|    Fare|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+--------+-----+--------+
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599| 71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|   7.925| null|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|    53.1| C123|       S|
|          9|       1|     3|Johnson, Mrs. Osc...|female|27.0|    0|    2|          347742| 11.1333| null|       S|
|         10|       1|     2|Nasser, Mrs. Nich...|female|14.0|    1|    0|          237736| 30.0708| null|       C|
|         11|       1|     3|Sandstrom, Miss. ...|female| 4.0|    1|    1|         PP 9549|    16.7|   G6|       S|
|         12|       1|     1|Bonnell, Miss. El...|female|58.0|    0|    0|          113783|   26.55| C103|       S|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female|55.0|    0|    0|          248706|    16.0| null|       S|
|         18|       1|     2|Williams, Mr. Cha...|  male|null|    0|    0|          244373|    13.0| null|       S|
|         20|       1|     3|Masselmani, Mrs. ...|female|null|    0|    0|            2649|   7.225| null|       C|
|         22|       1|     2|Beesley, Mr. Lawr...|  male|34.0|    0|    0|          248698|    13.0|  D56|       S|
|         23|       1|     3|"McGowan, Miss. A...|female|15.0|    0|    0|          330923|  8.0292| null|       Q|
|         24|       1|     1|Sloper, Mr. Willi...|  male|28.0|    0|    0|          113788|    35.5|   A6|       S|
|         26|       1|     3|Asplund, Mrs. Car...|female|38.0|    1|    5|          347077| 31.3875| null|       S|
|         29|       1|     3|"O'Dwyer, Miss. E...|female|null|    0|    0|          330959|  7.8792| null|       Q|
|         32|       1|     1|Spencer, Mrs. Wil...|female|null|    1|    0|        PC 17569|146.5208|  B78|       C|
|         33|       1|     3|Glynn, Miss. Mary...|female|null|    0|    0|          335677|    7.75| null|       Q|
|         37|       1|     3|    Mamee, Mr. Hanna|  male|null|    0|    0|            2677|  7.2292| null|       C|
|         40|       1|     3|Nicola-Yarred, Mi...|female|14.0|    1|    0|            2651| 11.2417| null|       C|
|         44|       1|     2|Laroche, Miss. Si...|female| 3.0|    1|    2|   SC/Paris 2123| 41.5792| null|       C|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+--------+-----+--------+
only showing top 20 rows

In [0]:
#Selecionando Colunas
df_titanic.select("Name").show()

+--------------------+
|                Name|
+--------------------+
|Braund, Mr. Owen ...|
|Cumings, Mrs. Joh...|
|Heikkinen, Miss. ...|
|Futrelle, Mrs. Ja...|
|Allen, Mr. Willia...|
|    Moran, Mr. James|
|McCarthy, Mr. Tim...|
|Palsson, Master. ...|
|Johnson, Mrs. Osc...|
|Nasser, Mrs. Nich...|
|Sandstrom, Miss. ...|
|Bonnell, Miss. El...|
|Saundercock, Mr. ...|
|Andersson, Mr. An...|
|Vestrom, Miss. Hu...|
|Hewlett, Mrs. (Ma...|
|Rice, Master. Eugene|
|Williams, Mr. Cha...|
|Vander Planke, Mr...|
|Masselmani, Mrs. ...|
+--------------------+
only showing top 20 rows

In [0]:
#Selecionar Colunas com Alias
df_titanic.select(df_titanic['Name'].alias('Nome')).show()

+--------------------+
|                Nome|
+--------------------+
|Braund, Mr. Owen ...|
|Cumings, Mrs. Joh...|
|Heikkinen, Miss. ...|
|Futrelle, Mrs. Ja...|
|Allen, Mr. Willia...|
|    Moran, Mr. James|
|McCarthy, Mr. Tim...|
|Palsson, Master. ...|
|Johnson, Mrs. Osc...|
|Nasser, Mrs. Nich...|
|Sandstrom, Miss. ...|
|Bonnell, Miss. El...|
|Saundercock, Mr. ...|
|Andersson, Mr. An...|
|Vestrom, Miss. Hu...|
|Hewlett, Mrs. (Ma...|
|Rice, Master. Eugene|
|Williams, Mr. Cha...|
|Vander Planke, Mr...|
|Masselmani, Mrs. ...|
+--------------------+
only showing top 20 rows

In [0]:
#Organizar as colunas
df_titanic.columns

Out[31]: ['PassengerId',
 'Survived',
 'Classe',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [0]:
#Organizar as colunas
df_titanic.select('Name','Survived','Classe',
                  'Sex', 'Age', 'SibSp', 'Parch', 
                  'Ticket', 'Fare', 'Cabin', 'Embarked').show()

+--------------------+--------+------+------+----+-----+-----+----------------+-------+-----+--------+
|                Name|Survived|Classe|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|
+--------------------+--------+------+------+----+-----+-----+----------------+-------+-----+--------+
|Braund, Mr. Owen ...|       0|     3|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|
|Cumings, Mrs. Joh...|       1|     1|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|
|Heikkinen, Miss. ...|       1|     3|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|
|Futrelle, Mrs. Ja...|       1|     1|female|35.0|    1|    0|          113803|   53.1| C123|       S|
|Allen, Mr. Willia...|       0|     3|  male|35.0|    0|    0|          373450|   8.05| null|       S|
|    Moran, Mr. James|       0|     3|  male|null|    0|    0|          330877| 8.4583| null|       Q|
|McCarthy, Mr. Tim...|       0|     1|  male|54.0|    0|    0|           17463|51.8625|  E46|       S|
|Palsson, Master. ...|       0|     3|  male| 2.0|    3|    1|          349909| 21.075| null|       S|
|Johnson, Mrs. Osc...|       1|     3|female|27.0|    0|    2|          347742|11.1333| null|       S|
|Nasser, Mrs. Nich...|       1|     2|female|14.0|    1|    0|          237736|30.0708| null|       C|
|Sandstrom, Miss. ...|       1|     3|female| 4.0|    1|    1|         PP 9549|   16.7|   G6|       S|
|Bonnell, Miss. El...|       1|     1|female|58.0|    0|    0|          113783|  26.55| C103|       S|
|Saundercock, Mr. ...|       0|     3|  male|20.0|    0|    0|       A/5. 2151|   8.05| null|       S|
|Andersson, Mr. An...|       0|     3|  male|39.0|    1|    5|          347082| 31.275| null|       S|
|Vestrom, Miss. Hu...|       0|     3|female|14.0|    0|    0|          350406| 7.8542| null|       S|
|Hewlett, Mrs. (Ma...|       1|     2|female|55.0|    0|    0|          248706|   16.0| null|       S|
|Rice, Master. Eugene|       0|     3|  male| 2.0|    4|    1|          382652| 29.125| null|       Q|
|Williams, Mr. Cha...|       1|     2|  male|null|    0|    0|          244373|   13.0| null|       S|
|Vander Planke, Mr...|       0|     3|female|31.0|    1|    0|          345763|   18.0| null|       S|
|Masselmani, Mrs. ...|       1|     3|female|null|    0|    0|            2649|  7.225| null|       C|
+--------------------+--------+------+------+----+-----+-----+----------------+-------+-----+--------+
only showing top 20 rows

In [0]:
#Filtros
df_titanic.filter(df_titanic["Sex"] == "male").show()

+-----------+--------+------+--------------------+----+----+-----+-----+----------+-------+-----------+--------+
|PassengerId|Survived|Classe|                Name| Sex| Age|SibSp|Parch|    Ticket|   Fare|      Cabin|Embarked|
+-----------+--------+------+--------------------+----+----+-----+-----+----------+-------+-----------+--------+
|          1|       0|     3|Braund, Mr. Owen ...|male|22.0|    1|    0| A/5 21171|   7.25|       null|       S|
|          5|       0|     3|Allen, Mr. Willia...|male|35.0|    0|    0|    373450|   8.05|       null|       S|
|          6|       0|     3|    Moran, Mr. James|male|null|    0|    0|    330877| 8.4583|       null|       Q|
|          7|       0|     1|McCarthy, Mr. Tim...|male|54.0|    0|    0|     17463|51.8625|        E46|       S|
|          8|       0|     3|Palsson, Master. ...|male| 2.0|    3|    1|    349909| 21.075|       null|       S|
|         13|       0|     3|Saundercock, Mr. ...|male|20.0|    0|    0| A/5. 2151|   8.05|       null|       S|
|         14|       0|     3|Andersson, Mr. An...|male|39.0|    1|    5|    347082| 31.275|       null|       S|
|         17|       0|     3|Rice, Master. Eugene|male| 2.0|    4|    1|    382652| 29.125|       null|       Q|
|         18|       1|     2|Williams, Mr. Cha...|male|null|    0|    0|    244373|   13.0|       null|       S|
|         21|       0|     2|Fynney, Mr. Joseph J|male|35.0|    0|    0|    239865|   26.0|       null|       S|
|         22|       1|     2|Beesley, Mr. Lawr...|male|34.0|    0|    0|    248698|   13.0|        D56|       S|
|         24|       1|     1|Sloper, Mr. Willi...|male|28.0|    0|    0|    113788|   35.5|         A6|       S|
|         27|       0|     3|Emir, Mr. Farred ...|male|null|    0|    0|      2631|  7.225|       null|       C|
|         28|       0|     1|Fortune, Mr. Char...|male|19.0|    3|    2|     19950|  263.0|C23 C25 C27|       S|
|         30|       0|     3| Todoroff, Mr. Lalio|male|null|    0|    0|    349216| 7.8958|       null|       S|
|         31|       0|     1|Uruchurtu, Don. M...|male|40.0|    0|    0|  PC 17601|27.7208|       null|       C|
|         34|       0|     2|Wheadon, Mr. Edwa...|male|66.0|    0|    0|C.A. 24579|   10.5|       null|       S|
|         35|       0|     1|Meyer, Mr. Edgar ...|male|28.0|    1|    0|  PC 17604|82.1708|       null|       C|
|         36|       0|     1|Holverson, Mr. Al...|male|42.0|    1|    0|    113789|   52.0|       null|       S|
|         37|       1|     3|    Mamee, Mr. Hanna|male|null|    0|    0|      2677| 7.2292|       null|       C|
+-----------+--------+------+--------------------+----+----+-----+-----+----------+-------+-----------+--------+
only showing top 20 rows

In [0]:
#Filtrar DF com 2 condições
df_titanic.filter((df_titanic["Sex"] == "male") & (df_titanic["Survived"] == "0")).show()

+-----------+--------+------+--------------------+----+----+-----+-----+---------------+-------+-----------+--------+
|PassengerId|Survived|Classe|                Name| Sex| Age|SibSp|Parch|         Ticket|   Fare|      Cabin|Embarked|
+-----------+--------+------+--------------------+----+----+-----+-----+---------------+-------+-----------+--------+
|          1|       0|     3|Braund, Mr. Owen ...|male|22.0|    1|    0|      A/5 21171|   7.25|       null|       S|
|          5|       0|     3|Allen, Mr. Willia...|male|35.0|    0|    0|         373450|   8.05|       null|       S|
|          6|       0|     3|    Moran, Mr. James|male|null|    0|    0|         330877| 8.4583|       null|       Q|
|          7|       0|     1|McCarthy, Mr. Tim...|male|54.0|    0|    0|          17463|51.8625|        E46|       S|
|          8|       0|     3|Palsson, Master. ...|male| 2.0|    3|    1|         349909| 21.075|       null|       S|
|         13|       0|     3|Saundercock, Mr. ...|male|20.0|    0|    0|      A/5. 2151|   8.05|       null|       S|
|         14|       0|     3|Andersson, Mr. An...|male|39.0|    1|    5|         347082| 31.275|       null|       S|
|         17|       0|     3|Rice, Master. Eugene|male| 2.0|    4|    1|         382652| 29.125|       null|       Q|
|         21|       0|     2|Fynney, Mr. Joseph J|male|35.0|    0|    0|         239865|   26.0|       null|       S|
|         27|       0|     3|Emir, Mr. Farred ...|male|null|    0|    0|           2631|  7.225|       null|       C|
|         28|       0|     1|Fortune, Mr. Char...|male|19.0|    3|    2|          19950|  263.0|C23 C25 C27|       S|
|         30|       0|     3| Todoroff, Mr. Lalio|male|null|    0|    0|         349216| 7.8958|       null|       S|
|         31|       0|     1|Uruchurtu, Don. M...|male|40.0|    0|    0|       PC 17601|27.7208|       null|       C|
|         34|       0|     2|Wheadon, Mr. Edwa...|male|66.0|    0|    0|     C.A. 24579|   10.5|       null|       S|
|         35|       0|     1|Meyer, Mr. Edgar ...|male|28.0|    1|    0|       PC 17604|82.1708|       null|       C|
|         36|       0|     1|Holverson, Mr. Al...|male|42.0|    1|    0|         113789|   52.0|       null|       S|
|         38|       0|     3|Cann, Mr. Ernest ...|male|21.0|    0|    0|     A./5. 2152|   8.05|       null|       S|
|         43|       0|     3| Kraeff, Mr. Theodor|male|null|    0|    0|         349253| 7.8958|       null|       C|
|         46|       0|     3|Rogers, Mr. Willi...|male|null|    0|    0|S.C./A.4. 23567|   8.05|       null|       S|
|         47|       0|     3|   Lennon, Mr. Denis|male|null|    1|    0|         370371|   15.5|       null|       Q|
+-----------+--------+------+--------------------+----+----+-----+-----+---------------+-------+-----------+--------+
only showing top 20 rows

In [0]:
#Filtrando algumas colunas com filtro
df_titanic.select("PassengerId","Name","Survived","Sex") \
           .filter((df_titanic["Sex"] == "male") & (df_titanic["Survived"] == "0")).show()

+-----------+--------------------+--------+----+
|PassengerId|                Name|Survived| Sex|
+-----------+--------------------+--------+----+
|          1|Braund, Mr. Owen ...|       0|male|
|          5|Allen, Mr. Willia...|       0|male|
|          6|    Moran, Mr. James|       0|male|
|          7|McCarthy, Mr. Tim...|       0|male|
|          8|Palsson, Master. ...|       0|male|
|         13|Saundercock, Mr. ...|       0|male|
|         14|Andersson, Mr. An...|       0|male|
|         17|Rice, Master. Eugene|       0|male|
|         21|Fynney, Mr. Joseph J|       0|male|
|         27|Emir, Mr. Farred ...|       0|male|
|         28|Fortune, Mr. Char...|       0|male|
|         30| Todoroff, Mr. Lalio|       0|male|
|         31|Uruchurtu, Don. M...|       0|male|
|         34|Wheadon, Mr. Edwa...|       0|male|
|         35|Meyer, Mr. Edgar ...|       0|male|
|         36|Holverson, Mr. Al...|       0|male|
|         38|Cann, Mr. Ernest ...|       0|male|
|         43| Kraeff, Mr. Theodor|       0|male|
|         46|Rogers, Mr. Willi...|       0|male|
|         47|   Lennon, Mr. Denis|       0|male|
+-----------+--------------------+--------+----+
only showing top 20 rows

In [0]:
#Criar novas colunas (usando a função lit)
df_titanic.withColumn('Nova_Coluna',lit(2018))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-323532469132119> in <module>
      1 #Criar novas colunas (usando a função lit)
      2 df_titanic.withColumn('Nova_Coluna',lit(2018))
----> 3 df_titanic.withColumn('Nova_Coluna2').show(10)

TypeError: withColumn() missing 1 required positional argument: 'col'

In [0]:
#Criar coluna condicional(usando função substring)
df_titanic.withColumn("Sub",substring('Sex',0,1)).show(5)

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+---+
|PassengerId|Survived|Classe|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|Sub|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+---+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|  m|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|  f|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|  f|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|  f|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| null|       S|  m|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+---+
only showing top 5 rows

In [0]:
#Criar coluna condicional (Concat /concat_ws)
df_titanic.withColumn("Concat", concat('Survived','Classe')).show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+------+
|PassengerId|Survived|Classe|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|Concat|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|    03|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|    11|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|    13|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|    11|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| null|       S|    03|
|          6|       0|     3|    Moran, Mr. James|  male|null|    0|    0|          330877| 8.4583| null|       Q|    03|
|          7|       0|     1|McCarthy, Mr. Tim...|  male|54.0|    0|    0|           17463|51.8625|  E46|       S|    01|
|          8|       0|     3|Palsson, Master. ...|  male| 2.0|    3|    1|          349909| 21.075| null|       S|    03|
|          9|       1|     3|Johnson, Mrs. Osc...|female|27.0|    0|    2|          347742|11.1333| null|       S|    13|
|         10|       1|     2|Nasser, Mrs. Nich...|female|14.0|    1|    0|          237736|30.0708| null|       C|    12|
|         11|       1|     3|Sandstrom, Miss. ...|female| 4.0|    1|    1|         PP 9549|   16.7|   G6|       S|    13|
|         12|       1|     1|Bonnell, Miss. El...|female|58.0|    0|    0|          113783|  26.55| C103|       S|    11|
|         13|       0|     3|Saundercock, Mr. ...|  male|20.0|    0|    0|       A/5. 2151|   8.05| null|       S|    03|
|         14|       0|     3|Andersson, Mr. An...|  male|39.0|    1|    5|          347082| 31.275| null|       S|    03|
|         15|       0|     3|Vestrom, Miss. Hu...|female|14.0|    0|    0|          350406| 7.8542| null|       S|    03|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female|55.0|    0|    0|          248706|   16.0| null|       S|    12|
|         17|       0|     3|Rice, Master. Eugene|  male| 2.0|    4|    1|          382652| 29.125| null|       Q|    03|
|         18|       1|     2|Williams, Mr. Cha...|  male|null|    0|    0|          244373|   13.0| null|       S|    12|
|         19|       0|     3|Vander Planke, Mr...|female|31.0|    1|    0|          345763|   18.0| null|       S|    03|
|         20|       1|     3|Masselmani, Mrs. ...|female|null|    0|    0|            2649|  7.225| null|       C|    13|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+------+
only showing top 20 rows

In [0]:
#Criar coluna condicional (Concat /concat_ws)
df_titanic.withColumn("Concat1", concat_ws('-','Survived','Classe')).show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+-------+
|PassengerId|Survived|Classe|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|Concat1|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+-------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|    0-3|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|    1-1|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|    1-3|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|    1-1|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| null|       S|    0-3|
|          6|       0|     3|    Moran, Mr. James|  male|null|    0|    0|          330877| 8.4583| null|       Q|    0-3|
|          7|       0|     1|McCarthy, Mr. Tim...|  male|54.0|    0|    0|           17463|51.8625|  E46|       S|    0-1|
|          8|       0|     3|Palsson, Master. ...|  male| 2.0|    3|    1|          349909| 21.075| null|       S|    0-3|
|          9|       1|     3|Johnson, Mrs. Osc...|female|27.0|    0|    2|          347742|11.1333| null|       S|    1-3|
|         10|       1|     2|Nasser, Mrs. Nich...|female|14.0|    1|    0|          237736|30.0708| null|       C|    1-2|
|         11|       1|     3|Sandstrom, Miss. ...|female| 4.0|    1|    1|         PP 9549|   16.7|   G6|       S|    1-3|
|         12|       1|     1|Bonnell, Miss. El...|female|58.0|    0|    0|          113783|  26.55| C103|       S|    1-1|
|         13|       0|     3|Saundercock, Mr. ...|  male|20.0|    0|    0|       A/5. 2151|   8.05| null|       S|    0-3|
|         14|       0|     3|Andersson, Mr. An...|  male|39.0|    1|    5|          347082| 31.275| null|       S|    0-3|
|         15|       0|     3|Vestrom, Miss. Hu...|female|14.0|    0|    0|          350406| 7.8542| null|       S|    0-3|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female|55.0|    0|    0|          248706|   16.0| null|       S|    1-2|
|         17|       0|     3|Rice, Master. Eugene|  male| 2.0|    4|    1|          382652| 29.125| null|       Q|    0-3|
|         18|       1|     2|Williams, Mr. Cha...|  male|null|    0|    0|          244373|   13.0| null|       S|    1-2|
|         19|       0|     3|Vander Planke, Mr...|female|31.0|    1|    0|          345763|   18.0| null|       S|    0-3|
|         20|       1|     3|Masselmani, Mrs. ...|female|null|    0|    0|            2649|  7.225| null|       C|    1-3|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+-------+
only showing top 20 rows

In [0]:
#Mudando o tipo da coluna de double para int
df_titanic = df_titanic.withColumn('Age',col('Age').cast(StringType()))

In [0]:
df_titanic.printSchema()

root
 |-- PassengerId: integer (nullable = true)
 |-- Survived: integer (nullable = true)
 |-- Classe: integer (nullable = true)
 |-- Name: string (nullable = true)
 |-- Sex: string (nullable = true)
 |-- Age: string (nullable = true)
 |-- SibSp: integer (nullable = true)
 |-- Parch: integer (nullable = true)
 |-- Ticket: string (nullable = true)
 |-- Fare: double (nullable = true)
 |-- Cabin: string (nullable = true)
 |-- Embarked: string (nullable = true)

In [0]:
#Criando função lambda
#Nesta função e possivel chamar pelo nome da variavel e passar um valor(coluna) para transformação
#Mais detalhes : https://www.youtube.com/watch?v=ycZZs4371us  minutos 50:00
fun_age_lambda = udf(lambda age: age.split('.')[0])

In [0]:
#Chamando a função lambda e filtrando o dataset
df_titanic.withColumn('Idade', fun_age_lambda('Age')).filter(df_titanic['Age'] != 'null').show()

+-----------+--------+------+--------------------+------+---+-----+-----+----------------+-------+-----+--------+-----+
|PassengerId|Survived|Classe|                Name|   Sex|Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|Idade|
+-----------+--------+------+--------------------+------+---+-----+-----+----------------+-------+-----+--------+-----+
|          1|       0|     3|Braund, Mr. Owen ...|  male| 22|    1|    0|       A/5 21171|   7.25| null|       S|   22|
|          2|       1|     1|Cumings, Mrs. Joh...|female| 38|    1|    0|        PC 17599|71.2833|  C85|       C|   38|
|          3|       1|     3|Heikkinen, Miss. ...|female| 26|    0|    0|STON/O2. 3101282|  7.925| null|       S|   26|
|          4|       1|     1|Futrelle, Mrs. Ja...|female| 35|    1|    0|          113803|   53.1| C123|       S|   35|
|          5|       0|     3|Allen, Mr. Willia...|  male| 35|    0|    0|          373450|   8.05| null|       S|   35|
|          7|       0|     1|McCarthy, Mr. Tim...|  male| 54|    0|    0|           17463|51.8625|  E46|       S|   54|
|          8|       0|     3|Palsson, Master. ...|  male|  2|    3|    1|          349909| 21.075| null|       S|    2|
|          9|       1|     3|Johnson, Mrs. Osc...|female| 27|    0|    2|          347742|11.1333| null|       S|   27|
|         10|       1|     2|Nasser, Mrs. Nich...|female| 14|    1|    0|          237736|30.0708| null|       C|   14|
|         11|       1|     3|Sandstrom, Miss. ...|female|  4|    1|    1|         PP 9549|   16.7|   G6|       S|    4|
|         12|       1|     1|Bonnell, Miss. El...|female| 58|    0|    0|          113783|  26.55| C103|       S|   58|
|         13|       0|     3|Saundercock, Mr. ...|  male| 20|    0|    0|       A/5. 2151|   8.05| null|       S|   20|
|         14|       0|     3|Andersson, Mr. An...|  male| 39|    1|    5|          347082| 31.275| null|       S|   39|
|         15|       0|     3|Vestrom, Miss. Hu...|female| 14|    0|    0|          350406| 7.8542| null|       S|   14|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female| 55|    0|    0|          248706|   16.0| null|       S|   55|
|         17|       0|     3|Rice, Master. Eugene|  male|  2|    4|    1|          382652| 29.125| null|       Q|    2|
|         19|       0|     3|Vander Planke, Mr...|female| 31|    1|    0|          345763|   18.0| null|       S|   31|
|         21|       0|     2|Fynney, Mr. Joseph J|  male| 35|    0|    0|          239865|   26.0| null|       S|   35|
|         22|       1|     2|Beesley, Mr. Lawr...|  male| 34|    0|    0|          248698|   13.0|  D56|       S|   34|
|         23|       1|     3|"McGowan, Miss. A...|female| 15|    0|    0|          330923| 8.0292| null|       Q|   15|
+-----------+--------+------+--------------------+------+---+-----+-----+----------------+-------+-----+--------+-----+
only showing top 20 rows